name:                servant-test
version:             0.1.0.0
github:              "mngrm3a/servant-test"
license:             BSD3
author:              "Daniel Priebe"
maintainer:          "tuxhq@icloud.com"
copyright:           "2019 Daniel Priebe"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mngrm3a/servant-test#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

executables:
  servant-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-server
    - servant-auth-server
    - warp
    - aeson
    - mtl
